from pathlib import Path

APP_NAME = "vietnamese_news_ir_system"
CONFIG_PATH = "configs"
CONFIG_FILE_NAME = "sample_config.json"

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
UTIL_DIR = PROJECT_ROOT / "util"
TRAIN_PATH = DATA_DIR / "train.parquet"
TEST_PATH = DATA_DIR / "test.parquet"
CORPUS_PATH = DATA_DIR / "corpus.parquet"
STOPWORDS_DICT_PATH = UTIL_DIR / "vietnamese-stopwords.txt"
CORPUS_JSON_PATH = DATA_DIR / "corpus.json"
TEST_QUERIES_JSON_PATH = DATA_DIR / "test_queries.json"
DOCUMENT_CORPUS_PICKLE_FILE = "document_corpus.pkl"
TERM_DOC_MATRIX_PICKLE_FILE = "term_doc_matrix.pkl"
TF_MATRIX_PICKLE_FILE = "tf_matrix.pkl"
IDF_MATRIX_PICKLE_FILE = "idf_matrix.pkl"
TF_IDF_MATRIX_PICKLE_FILE = "tf_idf_matrix.pkl"
# COLUMNS
# TRAIN_DATA
QUESTION_COLUMN = "question"
CONTEXT_LIST_COLUMN = "context_list"
QID_COLUMN = "qid"
CID_COLUMN = "cid"

# CORPUS_DATA
TEXT_COLUMN = "text"


# SPARK
OVERWRITE_WRITE_MODE = "overwrite"


# PATH OF FILES
TF_IDF_MATRIX_PICKLE_PATH = UTIL_DIR / TF_IDF_MATRIX_PICKLE_FILE
DOCUMENT_CORPUS_PICKLE_PATH = UTIL_DIR / DOCUMENT_CORPUS_PICKLE_FILE
TERM_DOC_MATRIX_PICKLE_PATH = UTIL_DIR / TERM_DOC_MATRIX_PICKLE_FILE
TF_MATRIX_PICKLE_PATH = UTIL_DIR / TF_MATRIX_PICKLE_FILE
IDF_MATRIX_PICKLE_PATH = UTIL_DIR / IDF_MATRIX_PICKLE_FILE
